package com.example.dramaserver.dao;

import com.example.dramaserver.domain.CateDrama;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface CateDramaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cate_drama
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cate_drama
     *
     * @mbg.generated
     */
    int insert(CateDrama record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cate_drama
     *
     * @mbg.generated
     */
    int insertSelective(CateDrama record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cate_drama
     *
     * @mbg.generated
     */
    CateDrama selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cate_drama
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CateDrama record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cate_drama
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CateDrama record);

    int updateCateDramaMsg(CateDrama record);

    int deleteCateDrama(Integer songId);

    List<CateDrama> allCateDrama();

    List<CateDrama> cateDramaOfDramaId(Integer dramaCateId);
}