package com.example.dramaserver.dao;

import com.example.dramaserver.domain.Drama;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface DramaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drama
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drama
     *
     * @mbg.generated
     */
    int insert(Drama record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drama
     *
     * @mbg.generated
     */
    int insertSelective(Drama record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drama
     *
     * @mbg.generated
     */
    Drama selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drama
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Drama record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drama
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Drama record);

    int updateDramaMsg(Drama record);

    int updateDramaPic(Drama record);

    int deleteDrama(Integer id);

    List<Drama> allDrama();

    List<Drama> dramaOfCategoryId(Integer categoryId);

    List<Drama> dramaOfId(Integer id);

    List<Drama> dramaOfCategoryName(String name);

    List<Drama> dramaOfName(String name);
}