package com.example.dramaserver.dao;

import com.example.dramaserver.domain.DramaCate;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface DramaCateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drama_cate
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drama_cate
     *
     * @mbg.generated
     */
    int insert(DramaCate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drama_cate
     *
     * @mbg.generated
     */
    int insertSelective(DramaCate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drama_cate
     *
     * @mbg.generated
     */
    DramaCate selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drama_cate
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DramaCate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drama_cate
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(DramaCate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drama_cate
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DramaCate record);

    int updateDramaCateMsg(DramaCate record);

    int updateDramaCatePic(DramaCate record);

    int deleteDramaCate(Integer id);

    List<DramaCate> allDramaCate();

    List<DramaCate> likeName(String name);

    List<DramaCate> dramaCateOfName(String name);

}