package com.example.dramaserver.domain;

import org.apache.commons.lang3.builder.ToStringBuilder;

public class CateDrama {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cate_drama.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cate_drama.drama_id
     *
     * @mbg.generated
     */
    private Integer dramaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cate_drama.drama_cate_id
     *
     * @mbg.generated
     */
    private Integer dramaCateId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cate_drama.id
     *
     * @return the value of cate_drama.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cate_drama.id
     *
     * @param id the value for cate_drama.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cate_drama.drama_id
     *
     * @return the value of cate_drama.drama_id
     *
     * @mbg.generated
     */
    public Integer getDramaId() {
        return dramaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cate_drama.drama_id
     *
     * @param dramaId the value for cate_drama.drama_id
     *
     * @mbg.generated
     */
    public void setDramaId(Integer dramaId) {
        this.dramaId = dramaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cate_drama.drama_cate_id
     *
     * @return the value of cate_drama.drama_cate_id
     *
     * @mbg.generated
     */
    public Integer getDramaCateId() {
        return dramaCateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cate_drama.drama_cate_id
     *
     * @param dramaCateId the value for cate_drama.drama_cate_id
     *
     * @mbg.generated
     */
    public void setDramaCateId(Integer dramaCateId) {
        this.dramaCateId = dramaCateId;
    }

    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this);
    }

}