package com.example.dramaserver.domain;

import org.apache.commons.lang3.builder.ToStringBuilder;

import java.util.Date;

public class Collect {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect.drama_id
     *
     * @mbg.generated
     */
    private Integer dramaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect.drama_cate_id
     *
     * @mbg.generated
     */
    private Integer dramaCateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect.id
     *
     * @return the value of collect.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect.id
     *
     * @param id the value for collect.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect.user_id
     *
     * @return the value of collect.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect.user_id
     *
     * @param userId the value for collect.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect.drama_id
     *
     * @return the value of collect.drama_id
     *
     * @mbg.generated
     */
    public Integer getDramaId() {
        return dramaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect.drama_id
     *
     * @param dramaId the value for collect.drama_id
     *
     * @mbg.generated
     */
    public void setDramaId(Integer dramaId) {
        this.dramaId = dramaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect.drama_cate_id
     *
     * @return the value of collect.drama_cate_id
     *
     * @mbg.generated
     */
    public Integer getDramaCateId() {
        return dramaCateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect.drama_cate_id
     *
     * @param dramaCateId the value for collect.drama_cate_id
     *
     * @mbg.generated
     */
    public void setDramaCateId(Integer dramaCateId) {
        this.dramaCateId = dramaCateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect.create_time
     *
     * @return the value of collect.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect.create_time
     *
     * @param createTime the value for collect.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this);
    }

}