package com.example.dramaserver.domain;

public class Rank {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rank.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rank.dramaId
     *
     * @mbg.generated
     */
    private Long dramaid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rank.userId
     *
     * @mbg.generated
     */
    private Long userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rank.score
     *
     * @mbg.generated
     */
    private Integer score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rank.id
     *
     * @return the value of rank.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rank.id
     *
     * @param id the value for rank.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rank.dramaId
     *
     * @return the value of rank.dramaId
     *
     * @mbg.generated
     */
    public Long getDramaId() {
        return dramaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rank.dramaId
     *
     * @param dramaid the value for rank.dramaId
     *
     * @mbg.generated
     */
    public void setDramaId(Long dramaid) {
        this.dramaid = dramaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rank.userId
     *
     * @return the value of rank.userId
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rank.userId
     *
     * @param userid the value for rank.userId
     *
     * @mbg.generated
     */
    public void setUserId(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rank.score
     *
     * @return the value of rank.score
     *
     * @mbg.generated
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rank.score
     *
     * @param score the value for rank.score
     *
     * @mbg.generated
     */
    public void setScore(Integer score) {
        this.score = score;
    }
}